// Generated by Flexc++ V2.03.04 on Fri, 13 Oct 2017 09:43:20 +0100

// $insert class_h
#include "Lexer.h"

// $insert namespace-use
    // UN-comment the next using-declaration if you want to use
    // symbols from the namespace dux without prefixing dux::
//using namespace dux;
