/**
** This header file is generated in gen/lexer.
** If you need to change it, please change there.
**/
// Generated by Flexc++ V2.03.04 on Sat, 14 Oct 2017 19:33:49 +0100

// $insert class_h
#include "Scanner.h"

// $insert namespace-use
    // UN-comment the next using-declaration if you want to use
    // symbols from the namespace dux without prefixing dux::
//using namespace dux;
